// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Individual struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Surname    string  `json:"surname"`
	Patronymic *string `json:"patronymic,omitempty"`
	Age        *int    `json:"age,omitempty"`
	Gender     *string `json:"gender,omitempty"`
	CountryID  *string `json:"country_id,omitempty"`
}

type IndividualFilter struct {
	Name       *string `json:"name,omitempty"`
	Surname    *string `json:"surname,omitempty"`
	Patronymic *string `json:"patronymic,omitempty"`
	AgeMin     *int    `json:"ageMin,omitempty"`
	AgeMax     *int    `json:"ageMax,omitempty"`
	Gender     *string `json:"gender,omitempty"`
	CountryID  *string `json:"country_id,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
